// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: extractor.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PDFExtractorService_UploadDocument_FullMethodName       = "/extractor.PDFExtractorService/UploadDocument"
	PDFExtractorService_SubmitDataPoints_FullMethodName     = "/extractor.PDFExtractorService/SubmitDataPoints"
	PDFExtractorService_GetExtractionResults_FullMethodName = "/extractor.PDFExtractorService/GetExtractionResults"
	PDFExtractorService_ListDocuments_FullMethodName        = "/extractor.PDFExtractorService/ListDocuments"
)

// PDFExtractorServiceClient is the client API for PDFExtractorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PDFExtractorServiceClient interface {
	UploadDocument(ctx context.Context, in *UploadDocumentRequest, opts ...grpc.CallOption) (*UploadDocumentResponse, error)
	SubmitDataPoints(ctx context.Context, in *SubmitDataPointsRequest, opts ...grpc.CallOption) (*SubmitDataPointsResponse, error)
	GetExtractionResults(ctx context.Context, in *GetResultsRequest, opts ...grpc.CallOption) (*GetResultsResponse, error)
	ListDocuments(ctx context.Context, in *ListDocumentsRequest, opts ...grpc.CallOption) (*ListDocumentsResponse, error)
}

type pDFExtractorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPDFExtractorServiceClient(cc grpc.ClientConnInterface) PDFExtractorServiceClient {
	return &pDFExtractorServiceClient{cc}
}

func (c *pDFExtractorServiceClient) UploadDocument(ctx context.Context, in *UploadDocumentRequest, opts ...grpc.CallOption) (*UploadDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadDocumentResponse)
	err := c.cc.Invoke(ctx, PDFExtractorService_UploadDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pDFExtractorServiceClient) SubmitDataPoints(ctx context.Context, in *SubmitDataPointsRequest, opts ...grpc.CallOption) (*SubmitDataPointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitDataPointsResponse)
	err := c.cc.Invoke(ctx, PDFExtractorService_SubmitDataPoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pDFExtractorServiceClient) GetExtractionResults(ctx context.Context, in *GetResultsRequest, opts ...grpc.CallOption) (*GetResultsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResultsResponse)
	err := c.cc.Invoke(ctx, PDFExtractorService_GetExtractionResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pDFExtractorServiceClient) ListDocuments(ctx context.Context, in *ListDocumentsRequest, opts ...grpc.CallOption) (*ListDocumentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDocumentsResponse)
	err := c.cc.Invoke(ctx, PDFExtractorService_ListDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PDFExtractorServiceServer is the server API for PDFExtractorService service.
// All implementations must embed UnimplementedPDFExtractorServiceServer
// for forward compatibility.
type PDFExtractorServiceServer interface {
	UploadDocument(context.Context, *UploadDocumentRequest) (*UploadDocumentResponse, error)
	SubmitDataPoints(context.Context, *SubmitDataPointsRequest) (*SubmitDataPointsResponse, error)
	GetExtractionResults(context.Context, *GetResultsRequest) (*GetResultsResponse, error)
	ListDocuments(context.Context, *ListDocumentsRequest) (*ListDocumentsResponse, error)
	mustEmbedUnimplementedPDFExtractorServiceServer()
}

// UnimplementedPDFExtractorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPDFExtractorServiceServer struct{}

func (UnimplementedPDFExtractorServiceServer) UploadDocument(context.Context, *UploadDocumentRequest) (*UploadDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadDocument not implemented")
}
func (UnimplementedPDFExtractorServiceServer) SubmitDataPoints(context.Context, *SubmitDataPointsRequest) (*SubmitDataPointsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitDataPoints not implemented")
}
func (UnimplementedPDFExtractorServiceServer) GetExtractionResults(context.Context, *GetResultsRequest) (*GetResultsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExtractionResults not implemented")
}
func (UnimplementedPDFExtractorServiceServer) ListDocuments(context.Context, *ListDocumentsRequest) (*ListDocumentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDocuments not implemented")
}
func (UnimplementedPDFExtractorServiceServer) mustEmbedUnimplementedPDFExtractorServiceServer() {}
func (UnimplementedPDFExtractorServiceServer) testEmbeddedByValue()                             {}

// UnsafePDFExtractorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PDFExtractorServiceServer will
// result in compilation errors.
type UnsafePDFExtractorServiceServer interface {
	mustEmbedUnimplementedPDFExtractorServiceServer()
}

func RegisterPDFExtractorServiceServer(s grpc.ServiceRegistrar, srv PDFExtractorServiceServer) {
	// If the following call panics, it indicates UnimplementedPDFExtractorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PDFExtractorService_ServiceDesc, srv)
}

func _PDFExtractorService_UploadDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PDFExtractorServiceServer).UploadDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PDFExtractorService_UploadDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PDFExtractorServiceServer).UploadDocument(ctx, req.(*UploadDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PDFExtractorService_SubmitDataPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitDataPointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PDFExtractorServiceServer).SubmitDataPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PDFExtractorService_SubmitDataPoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PDFExtractorServiceServer).SubmitDataPoints(ctx, req.(*SubmitDataPointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PDFExtractorService_GetExtractionResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PDFExtractorServiceServer).GetExtractionResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PDFExtractorService_GetExtractionResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PDFExtractorServiceServer).GetExtractionResults(ctx, req.(*GetResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PDFExtractorService_ListDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PDFExtractorServiceServer).ListDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PDFExtractorService_ListDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PDFExtractorServiceServer).ListDocuments(ctx, req.(*ListDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PDFExtractorService_ServiceDesc is the grpc.ServiceDesc for PDFExtractorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PDFExtractorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "extractor.PDFExtractorService",
	HandlerType: (*PDFExtractorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadDocument",
			Handler:    _PDFExtractorService_UploadDocument_Handler,
		},
		{
			MethodName: "SubmitDataPoints",
			Handler:    _PDFExtractorService_SubmitDataPoints_Handler,
		},
		{
			MethodName: "GetExtractionResults",
			Handler:    _PDFExtractorService_GetExtractionResults_Handler,
		},
		{
			MethodName: "ListDocuments",
			Handler:    _PDFExtractorService_ListDocuments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "extractor.proto",
}
